# COMP90024 GROUP48
# Yuhang Zhou     ID:1243037
# Jitao Feng      ID:1265994
# Hui Liu         ID:1336645
# Jihang Yu       ID:1341312
# Xinran Ren      ID:1309373

---
# Install dependencies on the host
- name: Install pip
  become: true
  ansible.builtin.apt:
    name: ["python3-dev", "python3-setuptools", "python3-pip"]
    state: latest
    update_cache: true
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update && sudo apt-get install python3-dev python3-setuptools python-pip

- name: Update pip
  ansible.builtin.pip:
    name: ["pip", "openstacksdk==0.62.0"]
    state: latest
# pip install --upgrade pip && pip install openstacksdk
