---
- name: Install and configure Python, Mastodon, and CouchDB and start harvester on VM
  hosts: localhost
  become: yes
  vars:
    couchdb_admin_username: Bob
    couchdb_admin_password: CCCansible48

  tasks:
    - name: install couchdb
      ansible.builtin.command:
        cmd: "sudo snap install couchdb"

    - name: start couchdb
      ansible.builtin.command:
        cmd: "sudo snap start couchdb"
    
    - name: Insert port under [chttpd]
      ansible.builtin.lineinfile:
        path: /var/snap/couchdb/current/etc/local.ini
        insertafter: '^\[chttpd\]'
        line: 'port = 5984'
      become: yes
      become_user: root

    - name: Insert bind_address under [chttpd]
      ansible.builtin.lineinfile:
        path: /var/snap/couchdb/current/etc/local.ini
        insertafter: 'port = 5984'
        line: 'bind_address = 0.0.0.0'
      become: yes
      become_user: root

    - name: Insert admin user under [admins]
      ansible.builtin.lineinfile:
        path: /var/snap/couchdb/current/etc/local.ini
        insertafter: '^\[admins\]'
        line: "{{ couchdb_admin_username }} = {{ couchdb_admin_password }}"
      become: yes
      become_user: root

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - nodejs
        state: latest
        update_cache: yes
    
    - name: Install required Python packages
      pip:
        name:
          - mastodon.py
          - couchdb
        state: latest
        executable: pip3

    - name: run mastodon_au harvester
      ansible.builtin.command:
        cmd: "nohup python3 mastodon_au.py &"
      async: 36000000
      poll: 0
        
    - name: run mastodon_aus_social harvester
      ansible.builtin.command:
        cmd: "nohup python3 mastodon_aus_social.py &"
      async: 36000000
      poll: 0
