# COMP90024 GROUP48
# Yuhang Zhou     ID:1243037
# Jitao Feng      ID:1265994
# Hui Liu         ID:1336645
# Jihang Yu       ID:1341312
# Xinran Ren      ID:1309373

---
- name: Install Python, Mastodon and start harvester on VM
  hosts: localhost
  become: yes

  tasks:  
    - name: Install required packages
      apt:
        name:
          - git
          - python3
          - python3-pip
          - nodejs
        state: latest
        update_cache: yes

    - name: Clone git repository
      git:
        repo: 'https://github.com/fcxsdyb/COMP90024.git'
        dest: '/home/ubuntu/Assignment2'

    - name: Install required Python packages
      pip:
        name:
          - mastodon.py
          - couchdb
          - textblob
          - argparse
        state: latest
        executable: pip3
      args:
        chdir: '/home/ubuntu/Assignment2/Harvester/harvester_ansible'

    - name: run mastodon_au harvester
      ansible.builtin.command:
        cmd: "python3 mastodon_au.py --token AfJXxavoZkTBBqqPK23U8jFTOb2j7bqar6EgCGMH3bs --url https://mastodon.au/"
      async: 3600000
      poll: 0
      args:
        chdir: '/home/ubuntu/Assignment2/Harvester/harvester_ansible'

    - name: run mastodon_au harvester
      ansible.builtin.command:
        cmd: "python3 mastodon_au.py --token 2nwIHJnHrDkZkFnzbFEgDZmsYTTgu8aXnutLRRgermg --url https://aus.social/"
      async: 3600000
      poll: 0
      args:
        chdir: '/home/ubuntu/Assignment2/Harvester/harvester_ansible'
